import { GoogleGenerativeAI } from "@google/generative-ai";

import fetch from "node-fetch";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

const API_KEY = process.env.GEMINI_API_KEY;

async function listModels() {
  const res = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models?key=${API_KEY}`,
  );
  const data = await res.json();
  console.log(data);
}

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const retry = async <T>(
  fn: () => Promise<T>,
  retries = 2,
  delay = 1000,
): Promise<T> => {
  try {
    return await fn();
  } catch (error) {
    if (retries <= 0) throw error;

    console.log(`Retrying... attempts left: ${retries}`);
    await sleep(delay);

    return retry(fn, retries - 1, delay * 2); // exponential backoff
  }
};

const MODELS = ["gemini-2.5-flash", "gemini-2.0-flash", "gemini-1.5-flash"];

// gemini-2.5-pro, gemini-2.0-flash
// listModels();

export const generateAIReviewer = async (text: string): Promise<string> => {
  const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

  const prompt = `
You are a STRICT academic study assistant.

Your ONLY task is to create or IMPROVE a REVIEWER from the provided material.

----------------------------------
🧠 CONTENT DETECTION (VERY IMPORTANT)
----------------------------------
First, analyze the content:

- If the content is RAW LESSON MATERIAL:
  → Create a NEW structured reviewer

- If the content is ALREADY A REVIEWER (e.g., has summaries, bullet points, key concepts):
  → DO NOT repeat it
  → DO NOT copy it
  → Instead, IMPROVE and ENHANCE it by:
     - Making explanations clearer
     - Adding missing key concepts
     - Simplifying complex ideas
     - Improving structure and readability
     - Adding better keypoints and definitions

----------------------------------
🚫 HARD RULES (MUST FOLLOW)
----------------------------------
- DO NOT answer quizzes, exercises, or activities
- DO NOT solve questions from the material
- DO NOT include answer keys from the document
- If the content contains:
  - Quiz
  - Test
  - Activity
  - Worksheet
  - Guide Questions
  → IGNORE those sections completely

- ONLY extract and explain LESSON CONTENT

----------------------------------
✅ WHAT YOU SHOULD DO
----------------------------------
From the VALID content, generate:

1. Key Concepts  
   - Bullet points  
   - Each must include:
     • Concept name  
     • ONE-SENTENCE KEYPOINT  

2. Detailed Summary  
   - Clear, simplified, student-friendly  
   - Break down complex ideas  

3. Concept Explanations  
   - 2–3 sentences per concept  
   - Focus on "how it works" or "why it matters"  

4. Quiz (GENERATED BY YOU)  
   - Create 3 NEW questions  
   - Include answers  
   - DO NOT reuse original questions  

5. Important Terms  
   - Term + simple definition (1 sentence)

----------------------------------
⚠️ SPECIAL CASES
----------------------------------
- If the content is MOSTLY a quiz/test:
  → Respond with:
  "The uploaded file appears to be a quiz or activity. Please provide lesson material to generate a reviewer."

----------------------------------
📄 OUTPUT FORMAT (STRICT)
----------------------------------

### Key Concepts
- Concept — One-sentence keypoint

### Detailed Summary
...

### Concept Explanations
- Concept:
  Explanation...

### Quiz
1. Question  
   Answer: ...

### Important Terms
- Term: Definition

----------------------------------
🚫 OUTPUT CLEANLINESS RULES
----------------------------------
- Do NOT repeat sections
- Do NOT duplicate headings
- Do NOT include "***" or "---"
- Avoid unnecessary markdown
- Keep output clean and consistent

----------------------------------
📘 CONTENT
----------------------------------
${text}
`;

  let lastError: any;

  for (const modelName of MODELS) {
    try {
      console.log(`Trying model: ${modelName}`);

      const model = genAI.getGenerativeModel({
        model: modelName,
      });

      const result = await retry(() => model.generateContent(prompt));

      const response = await result.response;
      const aiMessage = response.text();

      if (!aiMessage) {
        throw new Error("Empty response");
      }

      return aiMessage;
    } catch (error) {
      console.error(`Model ${modelName} failed:`, error);
      lastError = error;
    }
  }

  throw new Error("All models failed");
};
